import type { Metadata } from "next";
import { Montserrat, Fraunces, Inter } from "next/font/google";
import "./globals.css";

const monsterrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700"],
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Product preview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
